config/routes.rb
Viola::Application.routes.draw do
  resources :item_files

  resources :item_thumbnails

  resources :item_tags

  resources :item_props

  resources :items

  resources :storages

  

end

app/models/item_prop.rb
class ItemProp < ActiveRecord::Base
  belongs_to :item
end

app/controllers/item_props_controller.rb
class ItemPropsController < ApplicationController
  before_action :set_item_prop, only: [:show, :edit, :update, :destroy]

  # GET /item_props
  # GET /item_props.json
  def index
    @item_props = ItemProp.all
  end

  # GET /item_props/1
  # GET /item_props/1.json
  def show
  end

  # GET /item_props/new
  def new
    @item_prop = ItemProp.new
  end

  # GET /item_props/1/edit
  def edit
  end

  # POST /item_props
  # POST /item_props.json
  def create
    @item_prop = ItemProp.new(item_prop_params)

    respond_to do |format|
      if @item_prop.save
        format.html { redirect_to @item_prop, notice: 'Item prop was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item_prop }
      else
        format.html { render action: 'new' }
        format.json { render json: @item_prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_props/1
  # PATCH/PUT /item_props/1.json
  def update
    respond_to do |format|
      if @item_prop.update(item_prop_params)
        format.html { redirect_to @item_prop, notice: 'Item prop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item_prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_props/1
  # DELETE /item_props/1.json
  def destroy
    @item_prop.destroy
    respond_to do |format|
      format.html { redirect_to item_props_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_prop
      @item_prop = ItemProp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_prop_params
      params.require(:item_prop).permit(:item_id, :name, :value)
    end
end

app/helpers/item_props_helper.rb
module ItemPropsHelper
end

app/views/item_props/_form.html.slim
= form_for @item_prop do |f|
  - if @item_prop.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item_prop.errors.count, "error")} prohibited this item_prop from being saved:"
      ul
        - @item_prop.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :item
    = f.text_field :item
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :value
    = f.text_field :value
  .actions = f.submit 'Save'

app/views/item_props/edit.html.slim
h1 Editing item_prop

== render 'form'

= link_to 'Show', @item_prop
'|
= link_to 'Back', item_props_path

app/views/item_props/index.html.slim
h1 Listing item_props

table
  tr
    th Item
    th Name
    th Value
    th
    th
    th

  - @item_props.each do |item_prop|
    tr
      td = item_prop.item
      td = item_prop.name
      td = item_prop.value
      td = link_to 'Show', item_prop
      td = link_to 'Edit', edit_item_prop_path(item_prop)
      td = link_to 'Destroy', item_prop, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Item prop', new_item_prop_path

app/views/item_props/new.html.slim
h1 New item_prop

== render 'form'

= link_to 'Back', item_props_path

app/views/item_props/show.html.slim
p#notice = notice

p
  strong Item:
  = @item_prop.item
p
  strong Name:
  = @item_prop.name
p
  strong Value:
  = @item_prop.value

= link_to 'Edit', edit_item_prop_path(@item_prop)
'|
= link_to 'Back', item_props_path