config/routes.rb
Viola::Application.routes.draw do
  resources :item_files

  resources :item_thumbnails

  resources :item_tags

  resources :item_props

  resources :items

  resources :storages

  

end

app/models/item_tag.rb
class ItemTag < ActiveRecord::Base
  belongs_to :item
end

app/controllers/item_tags_controller.rb
class ItemTagsController < ApplicationController
  before_action :set_item_tag, only: [:show, :edit, :update, :destroy]

  # GET /item_tags
  # GET /item_tags.json
  def index
    @item_tags = ItemTag.all
  end

  # GET /item_tags/1
  # GET /item_tags/1.json
  def show
  end

  # GET /item_tags/new
  def new
    @item_tag = ItemTag.new
  end

  # GET /item_tags/1/edit
  def edit
  end

  # POST /item_tags
  # POST /item_tags.json
  def create
    @item_tag = ItemTag.new(item_tag_params)

    respond_to do |format|
      if @item_tag.save
        format.html { redirect_to @item_tag, notice: 'Item tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item_tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @item_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_tags/1
  # PATCH/PUT /item_tags/1.json
  def update
    respond_to do |format|
      if @item_tag.update(item_tag_params)
        format.html { redirect_to @item_tag, notice: 'Item tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_tags/1
  # DELETE /item_tags/1.json
  def destroy
    @item_tag.destroy
    respond_to do |format|
      format.html { redirect_to item_tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_tag
      @item_tag = ItemTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_tag_params
      params.require(:item_tag).permit(:item_id, :tag)
    end
end

app/helpers/item_tags_helper.rb
module ItemTagsHelper
end

app/views/item_tags/_form.html.slim
= form_for @item_tag do |f|
  - if @item_tag.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item_tag.errors.count, "error")} prohibited this item_tag from being saved:"
      ul
        - @item_tag.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :item
    = f.text_field :item
  .field
    = f.label :tag
    = f.text_field :tag
  .actions = f.submit 'Save'

app/views/item_tags/edit.html.slim
h1 Editing item_tag

== render 'form'

= link_to 'Show', @item_tag
'|
= link_to 'Back', item_tags_path

app/views/item_tags/index.html.slim
h1 Listing item_tags

table
  tr
    th Item
    th Tag
    th
    th
    th

  - @item_tags.each do |item_tag|
    tr
      td = item_tag.item
      td = item_tag.tag
      td = link_to 'Show', item_tag
      td = link_to 'Edit', edit_item_tag_path(item_tag)
      td = link_to 'Destroy', item_tag, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Item tag', new_item_tag_path

app/views/item_tags/new.html.slim
h1 New item_tag

== render 'form'

= link_to 'Back', item_tags_path

app/views/item_tags/show.html.slim
p#notice = notice

p
  strong Item:
  = @item_tag.item
p
  strong Tag:
  = @item_tag.tag

= link_to 'Edit', edit_item_tag_path(@item_tag)
'|
= link_to 'Back', item_tags_path