config/routes.rb
Viola::Application.routes.draw do
  resources :item_files

  resources :item_thumbnails

  resources :item_tags

  resources :item_props

  resources :items

  resources :storages

  

end

app/models/storage.rb
class Storage < ActiveRecord::Base
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  before_action :set_storage, only: [:show, :edit, :update, :destroy]

  # GET /storages
  # GET /storages.json
  def index
    @storages = Storage.all
  end

  # GET /storages/1
  # GET /storages/1.json
  def show
  end

  # GET /storages/new
  def new
    @storage = Storage.new
  end

  # GET /storages/1/edit
  def edit
  end

  # POST /storages
  # POST /storages.json
  def create
    @storage = Storage.new(storage_params)

    respond_to do |format|
      if @storage.save
        format.html { redirect_to @storage, notice: 'Storage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @storage }
      else
        format.html { render action: 'new' }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storages/1
  # PATCH/PUT /storages/1.json
  def update
    respond_to do |format|
      if @storage.update(storage_params)
        format.html { redirect_to @storage, notice: 'Storage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storages/1
  # DELETE /storages/1.json
  def destroy
    @storage.destroy
    respond_to do |format|
      format.html { redirect_to storages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storage
      @storage = Storage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def storage_params
      params.require(:storage).permit(:name, :path, :description, :device)
    end
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/views/storages/_form.html.slim
= form_for @storage do |f|
  - if @storage.errors.any?
    #error_explanation
      h2 = "#{pluralize(@storage.errors.count, "error")} prohibited this storage from being saved:"
      ul
        - @storage.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :path
    = f.text_field :path
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :device
    = f.number_field :device
  .actions = f.submit 'Save'

app/views/storages/edit.html.slim
h1 Editing storage

== render 'form'

= link_to 'Show', @storage
'|
= link_to 'Back', storages_path

app/views/storages/index.html.slim
h1 Listing storages

h2 test

table
  tr
    th Name
    th Path
    th Description
    th Device
    th
    th
    th

  - @storages.each do |storage|
    tr
      td = storage.name
      td = storage.path
      td = storage.description
      td = storage.device
      td = link_to 'Show', storage
      td = link_to 'Edit', edit_storage_path(storage)
      td = link_to 'Destroy', storage, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Storage', new_storage_path

app/views/storages/new.html.slim
h1 New storage

== render 'form'

= link_to 'Back', storages_path

app/views/storages/show.html.slim
p#notice = notice

p
  strong Name:
  = @storage.name
p
  strong Path:
  = @storage.path
p
  strong Description:
  = @storage.description
p
  strong Device:
  = @storage.device

= link_to 'Edit', edit_storage_path(@storage)
'|
= link_to 'Back', storages_path